// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNGguqNACKjkkoa2yZzVpE7wLdPtUEz8',
    appId: '1:122856981656:web:9c1e71f6d443e6e3df3ced',
    messagingSenderId: '122856981656',
    projectId: 'world-time-app-123',
    authDomain: 'world-time-app-123.firebaseapp.com',
    storageBucket: 'world-time-app-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBac2rAakgO7z4i9vp6qFOZ1uAwf8GCWd8',
    appId: '1:122856981656:android:b20fec900f075e7cdf3ced',
    messagingSenderId: '122856981656',
    projectId: 'world-time-app-123',
    storageBucket: 'world-time-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV8yCZoAxjY9eQbD_F1VeGuDk7YRMPv8o',
    appId: '1:122856981656:ios:2b6e9e6b1f8ece44df3ced',
    messagingSenderId: '122856981656',
    projectId: 'world-time-app-123',
    storageBucket: 'world-time-app-123.firebasestorage.app',
    iosClientId: '122856981656-3jk9s6ls86iehtuko2icopq8d7kmm61t.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbNGguqNACKjkkoa2yZzVpE7wLdPtUEz8',
    appId: '1:122856981656:web:8be7b95516fd337ddf3ced',
    messagingSenderId: '122856981656',
    projectId: 'world-time-app-123',
    authDomain: 'world-time-app-123.firebaseapp.com',
    storageBucket: 'world-time-app-123.firebasestorage.app',
  );
}
